name: tensorflow-development2
channels:
- anaconda
- conda-forge
- defaults

dependencies:
 - python=3.7
 - pip
 - numpy
 - matplotlib
 - pandas
 - tensorflow
 - notebook
 - nb_conda_kernels
 - jupyter_contrib_nbextensions
 - seaborn
 - pip:
   - ellipsinator
   - sklearn
